### PR TITLE
CoinbaseCreate devcontainer.json

### PR DESCRIPTION
**Pull request by khandidar663**

### CODE REVIEW

**Review by DanielaDudyova — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for DanielaDudyova @ 2024-01-07 22:25:53 UTC
User must have write permissions to review

**Review by Taterseth — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Taterseth @ 2024-01-11 08:56:35 UTC
User must have write permissions to review

**Review by Taterseth — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Taterseth @ 2024-01-11 08:57:04 UTC
User must have write permissions to review

**Review by alanekk3 — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for alanekk3 @ 2024-01-12 07:57:18 UTC
User must have write permissions to review

**Review by Taterseth — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Taterseth @ 2024-01-18 04:28:24 UTC
User must have write permissions to review

**Review by Taterseth — APPROVED** [review]

**Comment by cb-heimdall** [comment]
Review Error for Taterseth @ 2024-01-19 08:36:51 UTC
User must have write permissions to review

**Review by Taterseth — COMMENTED** [review]
you have my permission to review and change

**Comment by 31031969** [comment]
omar alfonso rodriguez borja cc 72158895 de barranquilla colombia cra 8c1 38b46 barrranquilla atlantico colombia  email omar72158895@gmail.com 
[LICENSE omar alfonso rodriguez borja.txt](https://github.com/coinbase/waas-sdk-react-native/files/14089779/LICENSE.omar.alfonso.rodriguez.borja.txt)
[35425669 (3) (1).pdf](https://github.com/coinbase/waas-sdk-react-native/files/14089782/35425669.3.1.pdf)
[1 (1) (1) (1) (2) (2) (1).pdf](https://github.com/coinbase/waas-sdk-react-native/files/14089784/1.1.1.1.2.2.1.pdf)

**Pull request closed without merging**
